version: '3'

services:
  frontend:
    image: frontend
    ports: 
      - 5000:5000
    container_name: frontend-container

  backend:
    image: backend
    ports:
      - 8080:8080
    container_name: backend-container