version: '3'

services:
    backend:
        image: backend-project
        ports:
            - 8080:8080
        environment:
            - REDIS_HOST=redis
            - POSTGRES_HOST=db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DATABASE=postgres
        depends_on:
            - db
            - redis
        container_name: backend-container-projects
    
    frontend:
        image: frontend-project
        ports:
            - 5000:5000
        container_name: frontend-container-projects
    
    redis:
        image: redis:alpine
        container_name: redis

    db:
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
        container_name: db

    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
        depends_on:
            - backend
            - frontend
        container_name: nginx